# Generated by Django 5.1.4 on 2024-12-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foundation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=255)),
                ('logo1', models.BinaryField(blank=True, null=True)),
                ('logo2', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
